### ISSUE TITLE
NL validation not working properly

### ISSUE THREAD

**Issue by stefandoorn** [sirprize/postal-code-validator#12]
A recent change only allows the `#### @@` format for The Netherlands. I can also see DHL describes this format. Unfortunately it's very common in The Netherlands to write it as `####@@` and all companies can accept this format. Would you be open to a PR to adjust this behavior again or will this library stick to the DHL formats?

**Comment by sirprize** [comment]
The validator can ignore whitespace by passing a value of `true` in the 3rd argument to `isValid()`
