### ISSUE TITLE
Postal codes in Vietnam

### ISSUE THREAD

**Issue by seamys** [sirprize/postal-code-validator#20]
https://github.com/sirprize/postal-code-validator/blob/27a576520f94d2b309e0ba08795c1df12501bba6/src/Validator.php#L294

https://en.wikipedia.org/wiki/Postal_codes_in_Vietnam

The following table is a list of postal codes in Vietnam (5 digits).[1]

**Comment by sirprize** [comment]
Thanks for this, fixed it
