### ISSUE TITLE
citation needed

### ISSUE THREAD

**Issue by xpavp03** [sirprize/postal-code-validator#7]
Postal code validator for all countries is an ambitious project because some people don't even know their own country's validation rules. There can be rare edge cases. Kudos for trying.

Before I can use your validator, I have to know I can trust your rules.

Your rules for Canada ('@#@ #@#', '@#@ #@') are more benevolent than what [Wikipedia](https://en.wikipedia.org/wiki/Postal_codes_in_Canada) says, and what my Canadian friend claims. Please note that I'm not saying that everything on Wikipedia is true.

Could you please tell me where you learned that Canadian postal code can also have only 5 characters? (Your second rule.)

It would be beneficial to provide links to sources about postal code rules of each country so that anyone can verify that for instance, your rules for Guinea-Bissau are up to date.

**Comment by sirprize** [comment]
...not that ambitious really, but for sure a good idea to specify the data source and provide an update. It is based on an older list published by DHL and definitely needed an update. Seems like DHL narrowed down the range of countries quite a bit. Update is done now, please find the source-link in the updated readme
